
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent for generating trading signals based on historical price patterns.
 *
 * - generateTradingSignals - A function that generates trading signals based on historical price patterns and a selected strategy.
 * - GenerateTradingSignalsInput - The input type for the generateTradingSignals function.
 * - GenerateTradingSignalsOutput - The return type for the generateTradingSignals function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTradingSignalsInputSchema = z.object({
  historicalData: z
    .string()
    .describe(
      'Historical price data as a JSON string. Each object should contain timestamp, open, high, low, close, and volume.'
    ),
  strategy: z
    .enum(['movingAverage', 'rsi', 'bollingerBands'])
    .describe('The trading strategy to use.'),
  riskLevel: z
    .enum(['high', 'medium', 'low'])
    .describe('The risk level to use for the trading strategy.'),
  // cryptocurrencyForAI is now included here as it's passed from BotControls
  cryptocurrencyForAI: z.string().optional().describe('The cryptocurrency symbol the AI should focus its analysis on, e.g., BTC, ETH. This provides context.'),
});
export type GenerateTradingSignalsInput = z.infer<typeof GenerateTradingSignalsInputSchema>;

const SignalItemSchema = z.object({
  signal: z.enum(['BUY', 'SELL', 'HOLD']).describe("The trading signal: BUY, SELL, or HOLD."),
  confidence: z.number().min(0).max(1).describe("The confidence level of the signal, from 0.0 to 1.0.")
});

const GenerateTradingSignalsOutputSchema = z.object({
  signals: z
    .string()
    .describe(
      'Trading signals as a JSON string representing an array of objects. Each object MUST have a "signal" (string: "BUY", "SELL", or "HOLD") and a "confidence" (number: 0.0 to 1.0). Example: \'[{"signal": "BUY", "confidence": 0.85}, {"signal": "HOLD", "confidence": 0.6}]\' '
    ),
  explanation: z
    .string()
    .describe('Detailed human-readable explanation of the generated trading signals and the reasoning behind them.'),
});
export type GenerateTradingSignalsOutput = z.infer<typeof GenerateTradingSignalsOutputSchema>;

export async function generateTradingSignals(
  input: GenerateTradingSignalsInput
): Promise<GenerateTradingSignalsOutput> {
  return generateTradingSignalsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTradingSignalsPrompt',
  input: {schema: GenerateTradingSignalsInputSchema},
  output: {schema: GenerateTradingSignalsOutputSchema},
  prompt: `You are an expert in financial markets and trading strategy for {{cryptocurrencyForAI}}.

You will analyze historical price patterns and generate trading signals based on the selected strategy and risk level.

Historical Data: {{{historicalData}}}
Strategy: {{{strategy}}}
Risk Level: {{{riskLevel}}}
Contextual Asset for Analysis: {{cryptocurrencyForAI}}

Based on this data, provide trading signals and explain your reasoning.

IMPORTANT: Your output for the 'signals' field MUST be a JSON string that represents an array of objects. Each object in the array MUST contain exactly two keys:
1.  "signal": A string with one of three values: "BUY", "SELL", or "HOLD".
2.  "confidence": A number between 0.0 and 1.0 (inclusive) representing the confidence in this signal.

Example of a valid JSON string for the 'signals' field:
'[{"signal": "BUY", "confidence": 0.85}, {"signal": "HOLD", "confidence": 0.60}]'
'[{"signal": "SELL", "confidence": 0.75}]'
'[{"signal": "HOLD", "confidence": 0.90}]'

If you cannot determine a strong BUY or SELL signal, provide a HOLD signal with appropriate confidence.
Ensure the JSON is perfectly formatted. Also include a detailed human-readable explanation in the 'explanation' field.
`,
});

const generateTradingSignalsFlow = ai.defineFlow(
  {
    name: 'generateTradingSignalsFlow',
    inputSchema: GenerateTradingSignalsInputSchema,
    outputSchema: GenerateTradingSignalsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);

