// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent for generating trading signals based on historical price patterns.
 *
 * - generateTradingSignals - A function that generates trading signals based on historical price patterns and a selected strategy.
 * - GenerateTradingSignalsInput - The input type for the generateTradingSignals function.
 * - GenerateTradingSignalsOutput - The return type for the generateTradingSignals function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTradingSignalsInputSchema = z.object({
  historicalData: z
    .string()
    .describe(
      'Historical price data as a JSON string. Each object should contain timestamp, open, high, low, close, and volume.'
    ),
  strategy: z
    .enum(['movingAverage', 'rsi', 'bollingerBands'])
    .describe('The trading strategy to use.'),
  riskLevel: z
    .enum(['high', 'medium', 'low'])
    .describe('The risk level to use for the trading strategy.'),
});
export type GenerateTradingSignalsInput = z.infer<typeof GenerateTradingSignalsInputSchema>;

const GenerateTradingSignalsOutputSchema = z.object({
  signals: z
    .string()
    .describe(
      'Trading signals, recommended actions like BUY, SELL, or HOLD, with confidence levels.'
    ),
  explanation: z
    .string()
    .describe('Explanation of the generated trading signals and reasoning.'),
});
export type GenerateTradingSignalsOutput = z.infer<typeof GenerateTradingSignalsOutputSchema>;

export async function generateTradingSignals(
  input: GenerateTradingSignalsInput
): Promise<GenerateTradingSignalsOutput> {
  return generateTradingSignalsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTradingSignalsPrompt',
  input: {schema: GenerateTradingSignalsInputSchema},
  output: {schema: GenerateTradingSignalsOutputSchema},
  prompt: `You are an expert in financial markets and trading strategy.

You will analyze historical price patterns and generate trading signals based on the selected strategy and risk level.

Historical Data: {{{historicalData}}}
Strategy: {{{strategy}}}
Risk Level: {{{riskLevel}}}

Based on this data, provide trading signals and explain your reasoning.

Output trading signals as a JSON array of objects. Each object should have a signal (BUY, SELL, HOLD) and a confidence level (0-1). Also include a detailed human readable explanation.
`,
});

const generateTradingSignalsFlow = ai.defineFlow(
  {
    name: 'generateTradingSignalsFlow',
    inputSchema: GenerateTradingSignalsInputSchema,
    outputSchema: GenerateTradingSignalsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
